export const EXCHANGE_RATE_FETCH_INIT = 'EXCHANGE_RATE_FETCH_INIT';
export const EXCHANGE_RATE_FETCH_SUCCESS = 'EXCHANGE_RATE_FETCH_SUCCESS';
export const EXCHANGE_RATE_FETCH_ERROR = 'EXCHANGE_RATE_FETCH_ERROR';

export const SET_CURRENCY_SELECTION = 'SET_CURRENCY_SELECTION';

export const SET_UI_DATA = 'SET_UI_DATA';
